language: node_js
node_js:
  - '8'
  - '9'
  - '10'
script:
  - cd packages/react-vis
  - npm run lint
  - npm run cover
after_success:
  - npm install -g coveralls
  - cat coverage/lcov.info | coveralls
